### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by stephenway** [jonathantneal/mdcss-theme-github#1]
I'm following the readme and doing everything as laid out, however my gulp task is returning that it can't find this theme module. I also installed this project separately after installing mdcss.

``` js
      require('mdcss')({
        theme: require('mdcss-theme-github')({
          title: 'UI',
          logo: 'logo.png',
          'examples.base': 'dist',
          'examples.css': ['docs.css']
        })
      }),
```

```
$ gulp docs
module.js:340
    throw err;
    ^

Error: Cannot find module 'mdcss-theme-github'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/Stephen/projects/project/gulpfile.js:57:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by asifshirazi** [comment]
@stephenway try this:

```
require('mdcss')({
    theme: require('mdcss-theme-github')({
        title: 'UI',
        logo: 'logo.png',
        examples: {
                base: 'dist',
                css: ['docs.css']
        }
    })
}),
```

**Comment by stephenway** [comment]
I've moved on from this issue and unfortunately deleted the branch I was testing on. Reopen if anyone else has this issue?
